### ISSUE TITLE
Game crashing on newest version

### ISSUE THREAD

**Issue by S-o-u-ll** [xyroc/DungeonCrawl#1]
It is crashing during launch up before the first loading screen I went back and put the new version of the mod in to test it since even though i found the log files they were in .log format and I couldn't figure out how to open them

 
2019-08-07 15:48:58,399 main WARN Disabling terminal, you're running in an unsupported environment.2019-08-07 15:48:58,399 main WARN Disabling terminal, you're running in an unsupported environment.[15:48:58.507] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username,  --version, forge-28.0.40, --gameDir, C:\Users\Documents\Curse\Minecraft\Instances\The Adventures of Halk 1.14.4, --assetsDir, --assetIndex, 1.14, --uuid, 74536b0306674c8e9415fc97e707d684, --accessToken, ????????, --userType, legacy, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 28.0.40, --fml.mcVersion, 1.14.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20190719.225934][15:48:58.511] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 3.1.1+59+e32e753 starting: java version 1.8.0_221 by Oracle Corporation[15:48:58.880] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust[15:49:00.375] [main/ERROR] [ne.mi.co.CoreModEngine/COREMOD]: Error occurred initializing CoreModjava.nio.file.NoSuchFileException: patches/client/IngameMenuScreen$1.js at com.sun.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:544) ~[zipfs.jar:1.8.0_221] {} at com.sun.nio.zipfs.ZipPath.newInputStream(ZipPath.java:645) ~[zipfs.jar:1.8.0_221] {} at com.sun.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:278) ~[zipfs.jar:1.8.0_221] {} at java.nio.file.Files.newInputStream(Unknown Source) ~[?:1.8.0_221] {} at java.nio.file.Files.newBufferedReader(Unknown Source) ~[?:1.8.0_221] {} at java.nio.file.Files.newBufferedReader(Unknown Source) ~[?:1.8.0_221] {} at net.minecraftforge.fml.loading.moddiscovery.CoreModFile.readCoreMod(CoreModFile.java:42) ~[forge-1.14.4-28.0.40.jar:?] {} at net.minecraftforge.coremod.CoreMod.initialize(CoreMod.java:35) ~[coremods-0.7.1-milestone.0.2+4070770.jar:0.7.1-milestone.0.2+4070770+3+4070770] {} at net.minecraftforge.coremod.CoreModEngine.initialize(CoreModEngine.java:71) ~[coremods-0.7.1-milestone.0.2+4070770.jar:0.7.1-milestone.0.2+4070770+3+4070770] {} at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_221] {} at net.minecraftforge.coremod.CoreModEngine.initializeCoreMods(CoreModEngine.java:65) ~[coremods-0.7.1-milestone.0.2+4070770.jar:0.7.1-milestone.0.2+4070770+3+4070770] {} at net.minecraftforge.coremod.CoreModProvider.getCoreModTransformers(CoreModProvider.java:17) ~[coremods-0.7.1-milestone.0.2+4070770.jar:0.7.1-milestone.0.2+4070770+3+4070770] {} at net.minecraftforge.fml.loading.FMLServiceProvider.transformers(FMLServiceProvider.java:133) ~[forge-1.14.4-28.0.40.jar:28.0] {} at cpw.mods.modlauncher.TransformationServiceDecorator.gatherTransformers(TransformationServiceDecorator.java:70) ~[modlauncher-3.1.1.jar:?] {} at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseServiceTransformers$6(TransformationServicesHandler.java:100) ~[modlauncher-3.1.1.jar:?] {} at java.util.HashMap$Values.forEach(Unknown Source) [?:1.8.0_221] {} at cpw.mods.modlauncher.TransformationServicesHandler.initialiseServiceTransformers(TransformationServicesHandler.java:100) [modlauncher-3.1.1.jar:?] {} at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:64) [modlauncher-3.1.1.jar:?] {} at cpw.mods.modlauncher.Launcher.run(Launcher.java:75) [modlauncher-3.1.1.jar:?] {} at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-3.1.1.jar:?] {}[15:49:00.682] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, forge-28.0.40, --gameDir, C:\Users\Documents\Curse\Minecraft\Instances\The Adventures of Halk 1.14.4, --assetsDir, C:\Users\Documents\Curse\Minecraft\Install\assets, --username,  --assetIndex, 1.14, --uuid, 74536b0306674c8e9415fc97e707d684, --accessToken, ????????, --userType, legacy, --versionType, release, --width, 1024, --height, 768][RandomPatches Minecraft Transformer]: Patching method: func_71384_a (func_71384_a)Initializing transformation  org.objectweb.asm.tree.ClassNode@2785db06Found method  org.objectweb.asm.tree.MethodNode@5fcd1f0aFound node  org.objectweb.asm.tree.LineNumberNode@7bbfc5ff[RandomPatches Entity Transformer]: Patching method: func_189511_e (func_189511_e)[RandomPatches Entity Transformer]: Patching method: func_70020_e (func_70020_e)Setting up BetterSprintingCore...Transforming livingTick (movement update)...Found entry point at 68.Transforming livingTick (sprinting)...Found insertion point at 268, skip point at 466.Transforming livingTick (super call)...Found insertion point at 899, skip point at 923.Finished BetterSprintingCore.Initializing transformation  org.objectweb.asm.tree.ClassNode@126f8f24Found method  org.objectweb.asm.tree.MethodNode@7fbf26fcFound node  org.objectweb.asm.tree.VarInsnNode@11c78080[RandomPatches ClientPlayerEntity Transformer]: Transforming class: net/minecraft/client/entity/player/ClientPlayerEntity[RandomPatches ClientPlayerEntity Transformer]: Patching method: func_70071_h_ (func_70071_h_)[15:49:02.786] [Client thread/INFO] [minecraft/Minecraft]: Setting user: Exception in thread "Client thread" [15:49:03.731] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException[15:49:03.732] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)[15:49:03.732] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)[15:49:03.732] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)[15:49:03.732] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: at cpw.mods.modlauncher.Launcher.run(Launcher.java:80)[15:49:03.732] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)[15:49:03.732] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.reflect.InvocationTargetException[15:49:03.732] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[15:49:03.732] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)[15:49:03.732] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)[15:49:03.732] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: at java.lang.reflect.Method.invoke(Unknown Source)[15:49:03.732] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)[15:49:03.732] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)[15:49:03.733] [Client thread/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: ... 4 more[15:49:03.733] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ExceptionInInitializerError[15:49:03.733] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.fml.ModContainer.<init>(ModContainer.java:71)[15:49:03.733] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.fml.DefaultModContainers$1.<init>(DefaultModContainers.java:27)[15:49:03.733] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.fml.DefaultModContainers.<clinit>(DefaultModContainers.java:26)[15:49:03.733] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.fml.ModLoadingContext.getActiveContainer(ModLoadingContext.java:44)[15:49:03.733] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.registries.GameData.checkPrefix(GameData.java:939)[15:49:03.734] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.registries.ForgeRegistryEntry.setRegistryName(ForgeRegistryEntry.java:45)[15:49:03.734] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.registries.ForgeRegistryEntry.setRegistryName(ForgeRegistryEntry.java:50)[15:49:03.734] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.registries.ForgeRegistryEntry.setRegistryName(ForgeRegistryEntry.java:32)[15:49:03.734] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:54)[15:49:03.734] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:65)[15:49:03.734] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.registries.NamespacedWrapper.func_218381_a(NamespacedWrapper.java:34)[15:49:03.734] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:230)[15:49:03.734] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraft.util.registry.Registry.func_218325_a(Registry.java:226)[15:49:03.735] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraft.util.SoundEvents.func_219592_a(SoundEvents.java:804)[15:49:03.735] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraft.util.SoundEvents.<clinit>(SoundEvents.java:7)[15:49:03.735] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraft.util.registry.Registry.lambda$static$0(Registry.java:78)[15:49:03.735] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraft.util.registry.Registry.lambda$static$37(Registry.java:247)[15:49:03.735] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at java.util.LinkedHashMap$LinkedEntrySet.forEach(Unknown Source)[15:49:03.735] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraft.util.registry.Registry.<clinit>(Registry.java:246)[15:49:03.735] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:34)[15:49:03.735] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraft.client.Minecraft.<init>(Minecraft.java:353)[15:49:03.735] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraft.client.main.Main.main(SourceFile:155)[15:49:03.735] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: ... 10 more[15:49:03.735] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NullPointerException[15:49:03.735] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.fml.ModLoadingException.<init>(ModLoadingException.java:56)[15:49:03.736] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.fml.ModLoadingException.lambda$fromEarlyException$0(ModLoadingException.java:64)[15:49:03.736] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)[15:49:03.736] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)[15:49:03.736] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at java.util.stream.AbstractPipeline.copyInto(Unknown Source)[15:49:03.736] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)[15:49:03.736] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)[15:49:03.736] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)[15:49:03.736] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at java.util.stream.AbstractPipeline.evaluate(Unknown Source)[15:49:03.736] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at java.util.stream.ReferencePipeline.forEach(Unknown Source)[15:49:03.736] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)[15:49:03.737] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)[15:49:03.737] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at java.util.stream.AbstractPipeline.copyInto(Unknown Source)[15:49:03.737] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)[15:49:03.737] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)[15:49:03.737] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at java.util.stream.AbstractPipeline.evaluate(Unknown Source)[15:49:03.737] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at java.util.stream.ReferencePipeline.collect(Unknown Source)[15:49:03.737] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.fml.ModLoader.<init>(ModLoader.java:114)[15:49:03.737] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.fml.ModLoader.get(ModLoader.java:143)[15:49:03.737] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: at net.minecraftforge.fml.ModLoadingStage.<clinit>(ModLoadingStage.java:40)[15:49:03.737] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: ... 32 moreJava HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0

**Comment by xyroc** [comment]
And it is working if you remove Dungeon Crawl?

**Comment by S-o-u-ll** [comment]
yes it works if its removed or if I use the DungeonCrawl-1.14.4-1.2.0 version

**Comment by xyroc** [comment]
There is hardly a difference between 1.14.4-1.2.0 and 1.14.4-1.2.1. I just changed the required forge version.

**Comment by xyroc** [comment]
Can you show me the entire log? Btw you can open .log files with Winrar (its the zip format or sth similiar)

**Comment by S-o-u-ll** [comment]
yeah that seems like the problem then the adventures of halk modpack I added your mod to was using forge-28,0.40

**Comment by xyroc** [comment]
oh
Well you need forge 28.0.45 or later for dungeoncrawl

**Comment by S-o-u-ll** [comment]
though on a separate note 1.2.0 crashed when I tried to equip any mine and slash mod equipment

**Comment by xyroc** [comment]
1.14.4-1.1.0 should work with older forge only

**Comment by S-o-u-ll** [comment]
yeah i see that now I guess ill have to make my own modpack because the adventurs of halk is fun but it has some things I dont like about it

**Comment by xyroc** [comment]
1.2.0 crashed if you right click a block. is that what you did?

**Comment by S-o-u-ll** [comment]
right clicked a mine and slash mod  equipement to equip it

**Comment by xyroc** [comment]
maybe you right clicked a block as well. i hope so :D

**Comment by S-o-u-ll** [comment]
did 1.2.0 crash if you right clicked a block or something?

**Comment by xyroc** [comment]
i will close this issue for now.

**Comment by xyroc** [comment]
yes it did.

**Comment by S-o-u-ll** [comment]
oh ok that makes sense. thx

**Comment by XYROC** [comment]
i mean i could create a version of 1.2.1 that works with older forge. thats not a big deal. interested? :D
