### ISSUE TITLE
[1.14.4] Crash on world gen

### ISSUE THREAD

**Issue by mcenderdragon** [xyroc/DungeonCrawl#17]
```
java.util.concurrent.CompletionException: net.minecraft.crash.ReportedException: Exception generating new chunk
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:961) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$6349/341156448.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51]
Caused by: net.minecraft.crash.ReportedException: Exception generating new chunk
	at net.minecraft.world.server.ChunkManager.lambda$null$17(ChunkManager.java:520) ~[?:?]
	at net.minecraft.world.server.ChunkManager$$Lambda$6351/630115393.apply(Unknown Source) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-2.0.24.jar:?]
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$19(ChunkManager.java:507) ~[?:?]
	at net.minecraft.world.server.ChunkManager$$Lambda$6336/1744525775.apply(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51]
	... 12 more
Caused by: java.lang.ClassCastException: futurepack.world.dimensions.menelaus.ChunkGeneratorMenelaus$WrapperMenelaus cannot be cast to net.minecraft.world.server.ServerWorld
	at xiroc.dungeoncrawl.dungeon.Dungeon$Start.func_214625_a(Dungeon.java:145) ~[?:1.6.1]
	at net.minecraft.world.gen.ChunkGenerator.func_222533_a(ChunkGenerator.java:162) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$2(ChunkStatus.java:41) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$1573/1429830933.doWork(Unknown Source) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:196) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$null$17(ChunkManager.java:509) ~[?:?]
	at net.minecraft.world.server.ChunkManager$$Lambda$6351/630115393.apply(Unknown Source) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-2.0.24.jar:?]
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$19(ChunkManager.java:507) ~[?:?]
	at net.minecraft.world.server.ChunkManager$$Lambda$6336/1744525775.apply(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51]
	... 12 more
```

DungeonCrawl-1.14.4-1.6.1.jar

**Comment by mcenderdragon** [comment]
You cast everything to a ServerWorld, but its only declared as a IWorld. https://github.com/XYROC/DungeonCrawl/blob/1.14.4/src/main/java/xiroc/dungeoncrawl/dungeon/Dungeon.java#L145

**Comment by mcenderdragon** [comment]
DungeonPlacementEvent has to also change to a IWorld.

**Comment by Yamza** [comment]
Looks like this exists in 1.15.2 as well https://hatebin.com/stjytmgwrz

**Comment by Divineaspect** [comment]
Here's a 1.14 crash log https://pastebin.com/Nf6KS9Km
