### ISSUE TITLE
Server crash: Quark incompatibility?

### ISSUE THREAD

**Issue by MJRamon** [xyroc/DungeonCrawl#57]
forge-1.16.4-35.1.10
DungeonCrawl-1.16.3-2.2.2
Quark-r2.4-283

Even though "World" module of Quark is disabled.

```
[01џэт2021 09:27:38.855] [main/INFO] [Dungeon Crawl/]: Loading C:\servers\config\DungeonCrawl\config.json
[01џэт2021 09:27:38.864] [main/INFO] [Dungeon Crawl/]: Loading C:\servers\config\DungeonCrawl\loot\specialItemTags.json
[01џэт2021 09:27:38.945] [main/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 23
	Listeners:
		0: HIGH
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2652/2117012526@1ab7d58b
		2: net.minecraftforge.eventbus.EventBus$$Lambda$2652/2117012526@40e7ff8e
		3: net.minecraftforge.eventbus.EventBus$$Lambda$2652/2117012526@7ac56d0e
		4: ASM: class com.infamous.dungeons_mobs.worldgen.BiomeSpawnEntries onBiomeLoadingEvent(Lnet/minecraftforge/event/world/BiomeLoadingEvent;)V
		5: ASM: xiroc.dungeoncrawl.DungeonCrawl@23dffb22 onBiomeLoad(Lnet/minecraftforge/event/world/BiomeLoadingEvent;)V
		6: ASM: class com.girafi.waddles.init.PenguinSpawn addSpawn(Lnet/minecraftforge/event/world/BiomeLoadingEvent;)V
		7: net.minecraftforge.eventbus.EventBus$$Lambda$2652/2117012526@5cec6d6
		8: net.minecraftforge.eventbus.EventBus$$Lambda$2652/2117012526@21714069
		9: ASM: class com._idrae.towers_of_the_wild.events.TowersOfTheWildEventSubscriber onBiomeLoaded(Lnet/minecraftforge/event/world/BiomeLoadingEvent;)V
		10: ASM: class com.infamous.ice_ice_baby.worldgen.BiomeSpawnEntries onBiomeLoad(Lnet/minecraftforge/event/world/BiomeLoadingEvent;)V
		11: NORMAL
		12: ASM: com.github.alexthe666.alexsmobs.AlexsMobs@2bdf5e85 onBiomeLoadFromJSON(Lnet/minecraftforge/event/world/BiomeLoadingEvent;)V
		13: net.minecraftforge.eventbus.EventBus$$Lambda$2652/2117012526@5e15d046
		14: ASM: com.chrisgli.gemsnjewels.Main@15bd74b1 onBiomeLoad(Lnet/minecraftforge/event/world/BiomeLoadingEvent;)V
		15: net.minecraftforge.eventbus.EventBus$$Lambda$2652/2117012526@f696b97
		16: ASM: class com.infamous.dungeons_mobs.worldgen.BiomeSpawnEntries onBiomeLoadingEventForVariants(Lnet/minecraftforge/event/world/BiomeLoadingEvent;)V
		17: net.minecraftforge.eventbus.EventBus$$Lambda$2652/2117012526@7c62f4da
		18: ASM: class net.blay09.mods.waystones.worldgen.ModWorldGen onBiomeLoading(Lnet/minecraftforge/event/world/BiomeLoadingEvent;)V
		19: ASM: class com.tm.cspirit.world.EntitySpawns onBiomeLoaded(Lnet/minecraftforge/event/world/BiomeLoadingEvent;)V
		20: net.minecraftforge.eventbus.EventBus$$Lambda$2652/2117012526@57bb8137
		21: net.minecraftforge.eventbus.EventBus$$Lambda$2652/2117012526@27dcec66
		22: net.minecraftforge.eventbus.EventBus$$Lambda$2652/2117012526@632d0ed9
		23: ASM: class vazkii.quark.base.world.WorldGenHandler onBiomesLoaded(Lnet/minecraftforge/event/world/BiomeLoadingEvent;)V
		24: ASM: class vazkii.quark.base.world.EntitySpawnHandler onBiomeLoaded(Lnet/minecraftforge/event/world/BiomeLoadingEvent;)V
		25: net.minecraftforge.eventbus.EventBus$$Lambda$2652/2117012526@882f242
		26: LOW
		27: net.minecraftforge.eventbus.EventBus$$Lambda$2652/2117012526@33b685c
		28: net.minecraftforge.eventbus.EventBus$$Lambda$2652/2117012526@43441b81
java.lang.NullPointerException
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_236266_a_(SourceFile:22)
	at java.util.function.Function.lambda$andThen$1(Unknown Source)
	at com.mojang.serialization.codecs.KeyDispatchCodec.getCodec(KeyDispatchCodec.java:123)
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$new$0(KeyDispatchCodec.java:46)
	at com.mojang.serialization.codecs.KeyDispatchCodec.encode(KeyDispatchCodec.java:79)
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96)
	at vazkii.quark.base.world.WorldGenHandler.onBiomesLoaded(WorldGenHandler.java:146)
	at net.minecraftforge.eventbus.ASMEventHandler_644_WorldGenHandler_onBiomesLoaded_BiomeLoadingEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.common.ForgeHooks.enhanceBiome(ForgeHooks.java:902)
	at net.minecraft.world.biome.Biome.lambda$null$8(Biome.java:75)
	at com.mojang.datafixers.util.Function8.lambda$null$6(Function8.java:22)
	at com.mojang.datafixers.util.Function4.lambda$null$2(Function4.java:14)
	at com.mojang.serialization.DataResult$Instance.ap2(DataResult.java:315)
	at com.mojang.datafixers.kinds.Applicative.ap4(Applicative.java:84)
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$7.decode(RecordCodecBuilder.java:404)
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107)
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52)
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52)
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91)
	at com.mojang.serialization.Decoder.parse(Decoder.java:18)
	at net.minecraft.util.registry.WorldSettingsImport$IResourceAccess$RegistryAccess.func_241879_a(WorldSettingsImport.java:236)
	at net.minecraft.util.registry.WorldSettingsImport.func_241805_a_(WorldSettingsImport.java:131)
	at net.minecraft.util.registry.WorldSettingsImport.lambda$decode$5(WorldSettingsImport.java:105)
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
	at net.minecraft.util.registry.WorldSettingsImport.func_241797_a_(WorldSettingsImport.java:104)
	at net.minecraft.util.registry.DynamicRegistries.func_243610_a(DynamicRegistries.java:144)
	at net.minecraft.util.registry.DynamicRegistries.func_243608_a(DynamicRegistries.java:132)
	at net.minecraft.util.registry.WorldSettingsImport.func_244336_a(WorldSettingsImport.java:53)
	at net.minecraft.util.registry.DynamicRegistries.func_239770_b_(DynamicRegistries.java:85)
	at net.minecraft.server.Main.main(Main.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)

[01џэт2021 09:27:38.988] [main/FATAL] [net.minecraft.server.Main/]: Failed to start the minecraft server
java.lang.NullPointerException: null
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_236266_a_(SourceFile:22) ~[?:?]
	at java.util.function.Function.lambda$andThen$1(Unknown Source) ~[?:1.8.0_271]
	at com.mojang.serialization.codecs.KeyDispatchCodec.getCodec(KeyDispatchCodec.java:123) ~[?:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$new$0(KeyDispatchCodec.java:46) ~[?:?]
	at com.mojang.serialization.codecs.KeyDispatchCodec.encode(KeyDispatchCodec.java:79) ~[?:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96) ~[?:?]
	at vazkii.quark.base.world.WorldGenHandler.onBiomesLoaded(WorldGenHandler.java:146) ~[quark:r2.4-283]
	at net.minecraftforge.eventbus.ASMEventHandler_644_WorldGenHandler_onBiomesLoaded_BiomeLoadingEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.common.ForgeHooks.enhanceBiome(ForgeHooks.java:902) ~[forge:?]
	at net.minecraft.world.biome.Biome.lambda$null$8(Biome.java:75) ~[?:?]
	at com.mojang.datafixers.util.Function8.lambda$null$6(Function8.java:22) ~[?:?]
	at com.mojang.datafixers.util.Function4.lambda$null$2(Function4.java:14) ~[?:?]
	at com.mojang.serialization.DataResult$Instance.ap2(DataResult.java:315) ~[?:?]
	at com.mojang.datafixers.kinds.Applicative.ap4(Applicative.java:84) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$7.decode(RecordCodecBuilder.java:404) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[?:?]
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[?:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[?:?]
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[?:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[?:?]
	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[?:?]
	at net.minecraft.util.registry.WorldSettingsImport$IResourceAccess$RegistryAccess.func_241879_a(WorldSettingsImport.java:236) ~[?:?]
	at net.minecraft.util.registry.WorldSettingsImport.func_241805_a_(WorldSettingsImport.java:131) ~[?:?]
	at net.minecraft.util.registry.WorldSettingsImport.lambda$decode$5(WorldSettingsImport.java:105) ~[?:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[?:?]
	at net.minecraft.util.registry.WorldSettingsImport.func_241797_a_(WorldSettingsImport.java:104) ~[?:?]
	at net.minecraft.util.registry.DynamicRegistries.func_243610_a(DynamicRegistries.java:144) ~[?:?]
	at net.minecraft.util.registry.DynamicRegistries.func_243608_a(DynamicRegistries.java:132) ~[?:?]
	at net.minecraft.util.registry.WorldSettingsImport.func_244336_a(WorldSettingsImport.java:53) ~[?:?]
	at net.minecraft.util.registry.DynamicRegistries.func_239770_b_(DynamicRegistries.java:85) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:96) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.4-35.1.10.jar:35.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.4-35.1.10.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.4-35.1.10.jar:?]
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.4-35.1.10.jar:?]
```

**Comment by xyroc** [comment]
Are you sure this is actually related to Dungeon Crawl?
